### ISSUE TITLE
Invalid dereferenced expression is `@Nullable` error in Spring

### ISSUE THREAD

**Issue by sdeleuze** [uber/NullAway#1112]
In Spring Framework `ArgumentTypePreparedStatementSetter`, we have [this constructor](https://github.com/spring-projects/spring-framework/blob/0c6f5d7d297108be6592120acfa420a1341f853c/spring-jdbc/src/main/java/org/springframework/jdbc/core/ArgumentTypePreparedStatementSetter.java#L48-L56):

```
@SuppressWarnings("NullAway")
public ArgumentTypePreparedStatementSetter(@Nullable Object @Nullable [] args, int @Nullable [] argTypes) {
	if ((args != null && argTypes == null) || (args == null && argTypes != null) ||
			(args != null && args.length != argTypes.length)) {
		throw new InvalidDataAccessApiUsageException("args and argTypes parameters must match");
	}
	this.args = args;
	this.argTypes = argTypes;
}
```

Without `@SuppressWarnings("NullAway")`, we get a `dereferenced expression argTypes is @Nullable` error while IntelliJ IDEA is able to properly analyze the code flow to understand that `argTypes.length` can't throw a NPE.

**Comment by msridhar** [comment]
I see why this code is safe, but it took me a minute 🙂  NullAway's local dataflow analysis is not sophisticated enough to figure this out.  Handling it requires doing some sort of relational analysis (see [the SPA text, Section 7.2](https://cs.au.dk/~amoeller/spa/spa.pdf#page=99)), which I am a bit hesitant to add due to the potential increase in running time.  And, if/when we get time to improve the local dataflow analysis, we would probably prioritize fixing #98 first.

As a workaround, I think you could rewrite the `if` condition as (found with ChatGPT's help):
```java
	if ((args != null && argTypes == null)
         || (argTypes != null && (args == null || args.length != argTypes.length))) { ... }
```
This makes it more "obvious" that both `args` and `argTypes` are non-null when their lengths are checked, and I think NullAway won't warn on this version.

**Comment by sdeleuze** [comment]
Thanks for your feedback, I have replaced it by a variation of the workaround you proposed I created manually, thanks for the quick feedback!
