### ISSUE TITLE
Enhance -XepOpt:NullAway:UnannotatedSubPackages= to support wildcards as well. 

### ISSUE THREAD

**Issue by ajaygeorge** [uber/NullAway#151]
Currently the flag `-XepOpt:NullAway:UnannotatedSubPackages=` only takes in fully qualified package names . 

It will be convenient to support wildcards as well so that if we want to ignore say all the model package classes then we could use something like `-XepOpt:NullAway:UnannotatedSubPackages=*model*`

**Comment by lazaroclapp** [comment]
I tried to take a look into implementing this, and realized we already support it! 😅 

Basically, this option already takes in a form of regexp pattern. The caveat is that, because `.` is so common in package names, we don't acknowledge its meaning as "any character" and interpret it as the character literal for dot instead. 

I believe this will do exactly what you want:

`"-XepOpt:NullAway:UnannotatedSubPackages=[a-zA-Z0-9.]*model[a-zA-Z0-9.]*"`

Now, this is a bit of an undocumented feature at the moment, and might not be preserved in its current form forever. But I am uploading a change so that our tests break if the regexp support is ever dropped accidentally: #155.

@ajaygeorge Please let us know if this works for you!

**Comment by ajaygeorge** [comment]
thanks @lazaroclapp . That is working for me.
We can close this issue. Can you please update the README to add this example in so that it is clear for users of the api.

**Comment by msridhar** [comment]
We will update the docs to indicate this is supported.  Once that is done we will close this issue.

**Comment by lazaroclapp** [comment]
Added some info on our RegExp support [here](https://github.com/uber/NullAway/wiki/Configuration). Closing this for now, but feel free to reopen if the docs look unclear or there are any further questions on this.
