### ISSUE TITLE
Lombok compatibility?

### ISSUE THREAD

**Issue by gavenkoa** [uber/NullAway#193]
What is the status of Lombok compatibility with NullAway?

**Comment by msridhar** [comment]
There are various incompatibilities between Lombok and certain versions of Error Prone.  Additionally, I know that if you try to provide the Lombok jar on the classpath rather than the processorpath, but put the NullAway jar in the processorpath, then Lombok won't load (this is an issue with use of any Error Prone plugin check).  Beyond that, I don't know of any NullAway-specific compatibility issues with Lombok.
