### ISSUE TITLE
Model parseXXX methods of boxed primitives as having @NonNull parameter

### ISSUE THREAD

**Issue by msridhar** [uber/NullAway#269]
E.g., the parameter of `Long.parseLong(String)` should not be `null` or a `NumberFormatException` gets thrown.  We should model all the `parseXXX` methods of all the `java.lang` boxed primitive types.

**Comment by msridhar** [comment]
@shas19 any chance you'd have time to take a quick crack at this?

**Comment by shas19** [comment]
> @shas19 any chance you'd have time to take a quick crack at this?

Sure..

**Comment by lazaroclapp** [comment]
@msridhar @shas19 Sorry I didn't bother to test this until now, but this is actually sort of a breaking change. It breaks code that was passing `null` to `parseXXX` and then just catching a `NumberFormatException`, treating `null` as just another type of badly formatted number String. 

The argument for this change is that `NumberFormatException` is a `RuntimeException`, so this indeed catches real crashing errors when `NumberFormatException` is not being checked for.

The argument against is that, for code that is properly catching the exception, this makes making NullAway happy an awkward process. You basically have to either: a) include a conditional null check that does the same as the exception handler, b) call `Preconditions.checkNotNull(...)` and then catch both `NumberFormatException` and NPEs, c) `castToNonNull` and get non-fatals on perfectly good code.

Not clear what the right solution here would be, since there are indeed cases where `parseXXX` is being called without handling `NumberFormatException`. But, on the other hand, that code is just as broken on `""` as it is on `null`...

**Comment by msridhar** [comment]
Hrm. This is a strange case. One could argue that really `parseXXX` should throw an NPE when passed null rather than NumberFormatException, to avoid conflating the cases. But we can’t change that. Since others can add these library models if desired without modifying NullAway I am ok with reverting this change.

**Comment by lazaroclapp** [comment]
Hey @msridhar , do you remember if there was a real crash that prompted this issue, or is this a bit of a wishlist? Because if it would prevent real crashes, one solution, orthogonal to NullAway, is to make a separate checker that forces catching `NumberFormatException` (@shas19 's suggestion) when `parseXXX` is called. 

It's not ideal, because developers often know they are passing numeric data in, hence why NFE is not a checked exception, but it could be worth it at the level of Error Prone. So if this is all theoretical

**Comment by msridhar** [comment]
I've definitely seen a real crash caused by this issue, though I can't
recall exactly where.  Unfortunately this is just a bad API design and I
don't really know how the best way to work around it with a checker.  I
think ideally maybe there would be a combined check, where if you pass
something `@Nullable` to `parseXXX` *and* the `NumberFormatException` is
not caught, then emit a warning.  But doing such a thing within NullAway
would take some thinking / work and not sure if it generalizes.

**Comment by msridhar** [comment]
@lazaroclapp should we close this one as wontfix?  I haven't had any brilliant ideas on how to handle this case.

**Comment by msridhar** [comment]
Closing as wontfix for now, but we can re-open if we have a good idea on how to do this
