### ISSUE TITLE
False positive: field access in condition of 'assert' does not recognize field assignment on line above (in constructor)

### ISSUE THREAD

**Issue by cobratbq** [uber/NullAway#347]
Configuration:
- NullAway version 0.75, through Maven 3.6.1.
- Java run-time 11.
- Using the Java 11 compiler plug-in infrastructure directly, using argument line:  
  `<arg>-Xplugin:ErrorProne -Xep:NullAway:WARN -XepOpt:NullAway:AnnotatedPackages=net.java.otr4j</arg>`

Field access in assert condition in constructor, with field assignment on the line directly above the problematic one. See https://github.com/otr4j/otr4j/blob/master/src/main/java/net/java/otr4j/messages/SignatureX.java#L54

Result: `[WARNING] /home/danny/dev/otr/otr4j/src/main/java/net/java/otr4j/messages/SignatureX.java:[54,34] [NullAway] read of @NonNull field signature before initialization`

This problem does __not__ occur when `assert` line is replaced with `if`-statement.

**Comment by msridhar** [comment]
Thanks for the report!  This is definitely a bug.  It may relate to how assertions are modeled in our underlying dataflow analysis library.

**Comment by lazaroclapp** [comment]
@msridhar Can confirm I am able to repro this. Taking a quick look to see if I can figure out a fix, will at least do a PR with the repro if not.

**Comment by lazaroclapp** [comment]
So, basically, this is what's happening:

1) Because we skip assertions in the underlying dataflow analysis, `AnalysisResult.getNodesForTree(...)` will return `null` for every node inside an `assert` statement.
2) This means `AnalysisResult.getStoreBefore(...)` will also return `null` for the same tree.
3) The problem then is here, where we treat a missing store the same as a store not including the given path for initialization checking: https://github.com/uber/NullAway/blob/master/nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessAnalysis.java#L145 

I see two points of intervention here:
A) We explicitly filter any paths that are enclosed by `assert` in `NullAway.checkForReadBeforeInit`, unless assert checking is enabled in `Config`.
B) We treat "missing store" and "store does not include path" differently in `AccessPathNullnessAnalysis.getNonnullFieldsOfReceiverBefore` and `.getNonnullStaticFieldsBefore()`. This can be:
  B1) Throwing an exception
  B2) Adding a helper method like `AccessPathNullnessAnalysis.isAnalyzedTreePath(...)`

A is a bit hacky, but less likely to have a performance hit or cause us to miss something we don't intend to miss (not sure of all the cases under which the store can be `null`).

Also, there is:
C) Somehow make `assert` statements populate the dataflow analysis `Tree -> Node` and `Node -> Store` maps but not update the access paths on the store (e.g. treat all expressions there as "read-only" during dataflow.
This might need CF changes...

@msridhar thoughts?

**Comment by msridhar** [comment]
This is fixed by #348 I believe
