### ISSUE TITLE
Suggestion: Autopatch + castToNonNull mode

### ISSUE THREAD

**Issue by ZacSweers** [uber/NullAway#437]
One case I remember us handling at Uber was effectively baselining all existing nullability issues with `castToNonNull()` wrappers. What would you think of making this a configurable autopatch? I know there's already an option to specify a castToNonNull method, but maybe a `patchCastToNonNull` option that, when present, suggests wrapping nullable derefs with the specified method. This would allow an automated baselining of sorts in an existing codebase.

**Comment by lazaroclapp** [comment]
Hey Zac,

I believe this is actually already possible in NullAway if you pass the following options together: 

```
-Xep:NullAway:WARN -XepPatchChecks:NullAway -XepPatchLocation:IN_PLACE -XepOpt:NullAway:CastToNonNullMethod=[com.uber.nullaway.testdata.Util.castToNonNull] -XepOpt:NullAway:SuggestSuppressions=true
```

Replacing `[com.uber.nullaway.testdata.Util.castToNonNull]` for your `castToNonNull(...)` method with the same signature as the docs.

You can see a test for it [here](https://github.com/uber/NullAway/blob/cd93d7fd90f4a13f05cd49f5961ebac3193afbd2/nullaway/src/test/java/com/uber/nullaway/NullAwayAutoSuggestTest.java#L72).

Note that we don't have that option documented in part because we haven't used it internally in a long while, and things can break with it. Happy to look at reports of _how_ they break, of course.

**Comment by ZacSweers** [comment]
Ah! Great, I missed that doc. Thanks!
