### ISSUE TITLE
Allow configuring alternative Contract annotations name

### ISSUE THREAD

**Issue by anuraaga** [uber/NullAway#474]
Currently, the `Contract` annotations must be the jetbrains annotation

https://github.com/uber/NullAway/blob/master/nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractHandler.java#L78

It would be nice if we could configure a name for an alternative `Contract` annotation we provide, for example to have an internal annotation only for internal usage, without forcing the downstream user to end up with a dependency on the jetbrains annotation package. `compileOnly` type of dependency on the annotations don't work since they have a value and Java lint fails for that.

**Comment by lazaroclapp** [comment]
Sure! This makes sense to me. One reason the annotation is hard-coded is that the contract specification language (the string inside the value field of the annotation) is very much fixed to be a subset of what JetBrains uses, so, unlike `@Nullable`, this is not a generic support for all reasonable `@Contract` annotations. That said, if you just want to define your own annotation using NullAway's/JetBrain's syntax for the specification, I think we could and should allow this.

Not entirely sure if this should be a command line (`-XepOpt`) option for NullAway or a part of our pluggable library models. Can see the argument for either. (@msridhar, thoughts?).

This wouldn't be high priority for us internally, though. Would you be potentially interested in contributing a PR here after we discuss the approach, @anuraaga ? (Should be a fairly simple change: add a configuration option or library model, use that instead of the constant, add a test case)

**Comment by anuraaga** [comment]
Thanks @lazaroclapp - yeah with a decision on flag vs model, I could try to get a PR together.

**Comment by lazaroclapp** [comment]
I am happy to have this be a command line flag. We already do something similar for [external initialization annotations](https://github.com/uber/NullAway/wiki/Configuration#external-init-annotations). That said... @msridhar, any thoughts before @anuraaga spends time implementing something here?

**Comment by msridhar** [comment]
Hey, I'm totally fine with a command-line flag here; makes sense to support that to avoid needing to add in a library model just for this.  Thanks for the idea and the offer to help @anuraaga!

**Comment by lazaroclapp** [comment]
Closed by #476. Thanks, @anuraaga! (This should ship with the next NullAway release. Let us know if having this is urgent on your end, if not, we might wait until the next CF release to cut a new NullAway release, given the discussion in #468)

**Comment by anuraaga** [comment]
Hi @lazaroclapp - good to see #485 merged. Do you think there will be a release soon? While not urgent, been waiting a while to try this out :)

**Comment by msridhar** [comment]
@anuraaga our current plan is to create a new release for NullAway in early July, hopefully next week.  We want to depend on the upcoming version of the Checker Framework, which should be released this week

**Comment by msridhar** [comment]
FYI @anuraaga this change has made it into the NullAway 0.9.2 release.  Thanks for your patience!
